version: '3.5'

services:
  mysql:
    image: 'mysql:8'
    container_name: 'java-mysql'

    environment:
      - 'MYSQL_ROOT_PASSWORD=50151832L@tif'
      - 'MYSQL_DATABASE=credit_service'
    restart: always

  app:
    depends_on:
    - mysql
    restart: always
    build: ./
    container_name: "java-app"
    ports:
      - "8080:8080"
    command: "mvn clean spring-boot:run"
