package com.example.credit_service_project.validation;

public class ErrorsMessage {

    public static final String NOT_FOUND_ACCOUNT_MESSAGE = "NO SUCH ACCOUNT WAS FOUND!";
    public static final String NOT_FOUND_ACCOUNT_LIST_MESSAGE = "NO SUCH ACCOUNTS WAS CREATED!";
    public static final String NOT_FOUND_CARD_MESSAGE = "NO SUCH CARD WAS FOUND!";
    public static final String NOT_FOUND_ORDER_MESSAGE = "NO SUCH ORDERS WAS FOUND!";
    public static final String NOT_FOUND_OPERATION_MESSAGE = "NO SUCH OPERATION WAS FOUND!";
    public static final String NOT_FOUND_USER_MESSAGE = "NO SUCH USER WAS FOUND!";
    public static final String NOT_FOUND_NEAREST_PAYMENT_MESSAGE = "NEAREST PAYMENTS WAS FOUND!";
    public static final String NOT_FOUND_PRODUCT_MESSAGE = "NO SUCH PRODUCT WAS FOUND!";
    public static final String NOT_FOUND_AGREEMENT_MESSAGE = "NO SUCH AGREEMENT WAS FOUND!";
    public static final String NOT_FOUND_CREDIT_MESSAGE = "NO SUCH CREDIT WAS FOUND!";
    public static final String NOT_FOUND_ROLE_MESSAGE = "NO SUCH ROLE WAS FOUND!";
    public static final String UNKNOWN_TARGET_CURRENCY = "TARGET CURRENCY IS UNKNOWN!";
    public static final String UNKNOWN_SOURCE_CURRENCY = "SOURCE CURRENCY IS UNKNOWN!";

    public static final String UNABLE_INACCESSIBLE_CURRENCY = "THIS CURRENCY CANNOT BE PROCESSED BY OUR BANK YET!";
    public static final String NEGATIVE_BALANCE_EXCEPTION = "OPERATION SUM IS GREATER THAN BALANCE, PLEASE TOP UP YOUR ACCOUNT!";
    public static final String NEGATIVE_SUM_EXCEPTION = "THE AMOUNT TO REPLENISH IS NEGATIVE. PLEASE CHECK THE FORMAT AGAIN SUPPLY!";
    public static final String OPERATION_TYPE_CHANGE_MESSAGE = "CHANGE OPERATION CREDIT TO DEBIT IS IMPOSSIBLE!";
    public static final String AGREEMENT_CREATE_MESSAGE = "APPLICATION HAS NOT BEEN APPROVED IT IS IN THE PROCESS OF DISCLAIMER OR HAS BEEN OPENED, CREATION IS NOT POSSIBLE!";
    public static final String INSUFFICIENT_AMOUNT_MESSAGE = "THE AMOUNT YOU ENTERED IS NOT SUFFICIENT FOR SUFFICIENT REPAYMENT!";
    public static final String EARLY_PAYMENT_EXCEPTION_MESSAGE = "EARLY PAYMENT IS NOT POSSIBLE!";
    public static final String ACCOUNT_STATUS_EXCEPTION_MESSAGE = "ACCOUNT IS NOT ACTIVE ACTION IS NOT POSSIBLE!";
    public static final String CREDIT_IS_ALREADY_EXIST_EXCEPTION_MESSAGE = "THIS ACCOUNT HAVE ALREADY ONE CREDIT, OTHER CREDIT IS IMPOSSIBLE TO MAKE!";



}
