package com.example.credit_service_project.validation;

public class ErrorsMessage {

    public static final String NOT_FOUND_ACCOUNT_MESSAGE = "NO SUCH ACCOUNT WAS FOUND!";
    public static final String NOT_FOUND_ACCOUNT_LIST_MESSAGE = "NO SUCH ACCOUNTS WAS CREATED!";
    public static final String NOT_FOUND_CARD_MESSAGE = "NO SUCH CARD WAS FOUND!";
    public static final String NOT_FOUND_ORDER_MESSAGE = "NO SUCH ORDERS WAS FOUND!";
    public static final String NOT_FOUND_OPERATION_MESSAGE = "NO SUCH OPERATION WAS FOUND!";
    public static final String NOT_FOUND_CLIENT_MESSAGE = "NO SUCH CLIENT WAS FOUND!";
    public static final String NOT_FOUND_MANAGER_MESSAGE = "NO SUCH MANAGER WAS FOUND!";
    public static final String NOT_FOUND_NEAREST_PAYMENT_MESSAGE = "NEAREST PAYMENTS WAS FOUND!";
    public static final String NOT_FOUND_PRODUCT_MESSAGE = "NO SUCH PRODUCT WAS FOUND!";
    public static final String NOT_FOUND_AGREEMENT_MESSAGE = "NO SUCH AGREEMENT WAS FOUND!";
    public static final String NOT_FOUND_CREDIT_MESSAGE = "NO SUCH CREDIT WAS FOUND!";
    public static final String UNKNOWN_TARGET_CURRENCY = "TARGET CURRENCY IS UNKNOWN!";
    public static final String UNKNOWN_SOURCE_CURRENCY = "SOURCE CURRENCY IS UNKNOWN!";


    public static final String UNABLE_TO_ADD_ACCOUNT_MESSAGE = "THIS CLIENT WAS NOT FOUND, CREATING AN ACCOUNT IS IMPOSSIBLE!";
    public static final String UNABLE_TO_ADD_CARD_MESSAGE = "THIS ACCOUNT WAS NOT CREATED, ADDING A CARD IS IMPOSSIBLE!";
    public static final String UNABLE_TO_ADD_OPERATION_MESSAGE = "THIS ACCOUNT WAS NOT CREATED, CREATING AN OPERATION IS IMPOSSIBLE!";
    public static final String UNABLE_TO_ADD_PAYMENT_MESSAGE = "THIS ACCOUNT WAS NOT CREATED, ADDING A PAYMENT IS IMPOSSIBLE!";
    public static final String UNABLE_INACCESSIBLE_CURRENCY = "THIS CURRENCY CANNOT BE PROCESSED BY OUR BANK YET!";
    public static final String UNABLE_TO_ADD_CLIENT_MESSAGE = "THIS MANGER WAS NOT FOUND, ADDING A CLIENT IS IMPOSSIBLE!";
    public static final String NEGATIVE_BALANCE_EXCEPTION = "OPERATION SUM IS GREATER THAN BALANCE, PLEASE TOP UP YOUR ACCOUNT!";
    public static final String NEGATIVE_SUM_EXCEPTION = "THE AMOUNT TO REPLENISH IS NEGATIVE. PLEASE CHECK THE FORMAT AGAIN SUPPLY!";
    public static final String OPERATION_TYPE_CHANGE_MESSAGE = "CHANGE OPERATION CREDIT TO DEBIT IS IMPOSSIBLE!";
    public static final String AGREEMENT_CREATE_MESSAGE = "APPLICATION HAS NOT BEEN APPROVED IT IS IN THE PROCESS OF DISCLAIMER OR HAS BEEN OPENED, CREATION IS NOT POSSIBLE!";
    public static final String INSUFFICIENT_AMOUNT_MESSAGE = "THE AMOUNT YOU ENTERED IS NOT SUFFICIENT FOR SUFFICIENT REPAYMENT!";
    public static final String EARLY_PAYMENT_EXCEPTION_MESSAGE = "EARLY PAYMENT IS NOT POSSIBLE!";


}
